Hello World Project
shurichmond/Hello-World pull request #1
Opened 2023-03-28 22:01 UTC by shurichmond

### A Simple Hello world Project. Using HTML and CSS

- [x] Created an HTML file including h1 heading
- [x] Created a CSS file to style heading, giving it a color.
- [x] Set up Linters for the Project

2023-03-28 22:21 UTC, vickymarz requested changes
Hi @shurichmond, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️

- [ ] You have really tried, but then your linters are not correctly set up which can be confirmed since the linter result does not show a green tick in front of your commits. Therefore, I will encourage you to follow this [guide](https://github.com/microverseinc/linters-config/tree/master/html-css) step by step on how to properly install HTML and CSS linters

- [ ] Good job using the Microverse readme template 👍🏽. I think it will be better if you don't delete some sections from the readme (e.g Future features section) as you have done but rather customize all the sections of the readme by adding descriptive texts that relate to your project. Remember that only the FAQ section is optional, other sections are compulsory so fill them up (Remember to add descriptively how to properly get started with your project  😄

- [ ] Your branch name can be much more better if you can be more descriptive or clearer. You can use 'setup-linters' or 'hello-microverse'. Branch names like this better showcase what changes you introduced to your project. Therefore, I will encourage you to checkout to a new branch or edit the branch name on GitHub 😄 to use a more descriptive branch name.

Your branch name should be the name of the feature you are implementing👍🏽 

_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 17:00 UTC, adel-gu requested changes
# Status: REQUIRED CHANGES ♻️ 

Hi @shurichmond 👋🏼 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- All linters are passing now ✅ 
- The Future Features header is present now ✅ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 17:00 UTC, adel-gu commented on README.md
> +## 💻 Getting Started <a name="getting-started"></a>
- [ ] As requested by the previous reviewer, please consider adding a description customizing all the contents of your README file, help the readers how can they clone your repo, how they can use, what prerequisites they need to have...etc 👌😎

2023-03-31 17:00 UTC, adel-gu commented on README.md
> +
- [ ] As requested by the previous reviewer, please consider renaming your current branch name to something more meaningful instead of `feature-1`, a branch name should convey an action such as `setup-hello-microverse` or a feature name itself such as `hello-microverse` ✌

2023-03-31 17:00 UTC, adel-gu commented on README.md
> +This project is [MIT](./LICENSE.md) licensed.
- **[OPTIONAL]** Currently the license link is broken due to name reference issues, in the root folder you have the file `LICENSE` but for the link you referencing to it as `LICENSE.md`. I suggest adding the `md` extension to your file.

2023-04-01 12:08 UTC, merged